---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-claim
  namespace: assetvar
spec:
  storageClassName: hdd-ha
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi