---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: assetvar
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: timescaledb
  template:
    metadata:
      labels:
        k8s-app: timescaledb
    spec:

      # Essential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.workload/essential
                operator: In
                values:
                - "true"
      priorityClassName: essential

      containers:
      - name: timescaledb
        resources:
        image: timescale/timescaledb:2.1.1-pg13
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: timescaledb
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
      volumes:
      - name: timescaledb
        persistentVolumeClaim:
          claimName: timescaledb-claim
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: timescaledb
#   namespace: assetvar
# spec:
#   ports:
#   - port: 5432
#     targetPort: 5432
#   selector:
#     k8s-app: timescaledb

---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: assetvar
spec:
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    k8s-app: timescaledb
  type: LoadBalancer
  loadBalancerIP: 192.168.6.69
